language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install Sphinx sphinx_rtd_theme"
  - "pip install -e ."
script: py.test tests/ --cov bankkonto --cov-report term-missing
after_success:
  - coveralls

